### PR TITLE
implement support for spec.xrootd.replicas

### PR DESCRIPTION
**Pull request by sjha2048**
This pull request is for implementing the task given by Mentors regarding GSoC 2020.
please review it.

### CODE REVIEW

**Comment by sjha2048** [comment]
hey @fjammes can you please review this?

**Comment by fjammes** [comment]
This is a great start :-) Now, you should also update dynamically xrootd configuration to take in account the new replica. As mentioned in the excerpt of file configmap/xrootd/etc/xrootd.cf below, could you please try to implement the TODO feature inside the qserv-operator template engine (see qserv operator code, written in go)?

```
# TODO Generate xrootd redirector list using go template
set xrootddn = {{.XrootdRedirectorDn}}
all.manager ${xrootddn}-0.${xrootddn}:2131
all.manager ${xrootddn}-1.${xrootddn}:2131
```

In addition, could you please switch your PR to your own github repository so that other GSoc candidates could not see your work?

**Comment by sjha2048** [comment]
Sure thing!

Shall I close this pr then?

**Comment by fjammes** [comment]
You can continue in this PR, or open a new, private one so that nobody can "steal" your work.
An additional hint: Go function to update in order to implement this task is GenerateContainerConfigMap().

**Pull request closed without merging**
